주차 요그무 ><
KyungHyun-Cho/left-over-class pull request #23
Opened 2023-02-09 12:20 UTC by blucky8649

https://school.programmers.co.kr/learn/courses/30/lessons/92341

2023-02-09 12:33 UTC, hoxymola requested changes

2023-02-09 12:33 UTC, hoxymola commented on src/dongyeon-lee/230209/P92341.kt
> +    fun String.toMinutes() = split(":").let { it[0].toInt() * 60 + it[1].toInt() }
왜 동연님답지 않게 (h, m) -> 안쓰셨나요 😢

2023-02-09 12:33 UTC, hoxymola commented on src/dongyeon-lee/230209/P92341.kt
> +        dFee + (ceil(minus(dTime.toDouble()).coerceAtLeast(0.0).div(pTime)))  * pFee
this 가 없으니까 쉽지않네요..

2023-02-09 12:33 UTC, hoxymola commented on src/dongyeon-lee/230209/P92341.kt
> +            val  (t, num, _) = it.split(" ")
이렇게만 써도 될것같아요 !

```suggestion
            val (t, num) = it.split(' ')
```

2023-02-09 12:35 UTC, blucky8649 commented on src/dongyeon-lee/230209/P92341.kt
> +    fun String.toMinutes() = split(":").let { it[0].toInt() * 60 + it[1].toInt() }
헉 감사합니다 .

2023-02-09 13:29 UTC, KyungHyun-Cho commented on src/dongyeon-lee/230209/P92341.kt
> +                val diff = time -parkingMap.getOrDefault(num, 0)
```suggestion
                val diff = time - parkingMap.getOrDefault(num, 0)
```
컨벤션을 지켜주세요!

2023-02-09 13:34 UTC, KyungHyun-Cho commented on src/dongyeon-lee/230209/P92341.kt
> +                val diff = time -parkingMap.getOrDefault(num, 0)
```suggestion
                val diff = time - parkingMap.getValue(num)
```
어차피 위에서 containsKey로 검사했는데
getOrDefault 쓸 이유가 없네요

2023-02-13 13:40 UTC, hoxymola approved these changes
👍

2023-03-02 13:32 UTC, merged