프로그래머스 84512 모음사전
KyungHyun-Cho/left-over-class pull request #50
Opened 2023-03-01 08:15 UTC by KyungHyun-Cho

https://school.programmers.co.kr/learn/courses/30/lessons/84512

언제부터 완탐을 못하게 됐을까 ㅠㅠ

2023-03-01 11:55 UTC, hoxymola requested changes

2023-03-01 11:55 UTC, hoxymola commented on src/kyunghyun-cho/20230228/PGMS84512.kt
> +        throw Exception()
그냥 return 쓰면 안되나요 ?

2023-03-01 11:58 UTC, KyungHyun-Cho commented on src/kyunghyun-cho/20230228/PGMS84512.kt
> +        throw Exception()
그러면 불필요한 연산이 들어가서 답이 달라질거에요

2023-03-02 13:32 UTC, hoxymola approved these changes
👍 
아래꺼가 더 마음에 드네요

2023-03-02 13:35 UTC, merged